- name: "GO | Download Go"
  get_url: 
    url: "https://dl.google.com/go/go{{ go_version }}.linux-amd64.tar.gz"
    dest: /tmp/

- name: "GO | Install"
  unarchive:
    src: /tmp/go{{ go_version }}.linux-amd64.tar.gz
    dest: /usr/local
    remote_src: yes

- name: "GO | Load environment variables"
  lineinfile:
    path: /home/kasaiso/.bashrc
    state: present
    line: 'export PATH=$PATH:/usr/local/go/bin'